name: Tests on CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cpu:
    name: Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
      # Add Go bin directory to PATH for this workflow
      # GITHUB_PATH is a special file that GitHub Actions uses to modify PATH
      # Writing to this file adds the directory to the PATH for subsequent steps
      - name: Install gopls
        shell: bash
        run: go install golang.org/x/tools/gopls@latest
      - name: Set up Elixir
        if: runner.os != 'Windows'
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.4'
          otp-version: '26.1'

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: latest
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"
          terraform_wrapper: false
      - name: Install terraform-ls (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Write-Host "Installing terraform-ls via Chocolatey (most reliable method for Windows)"
          choco install terraform-ls --version 0.32.7 -y
      - name: Install terraform-ls (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          ver=0.32.7
          os=$(uname | tr '[:upper:]' '[:lower:]')
          echo "Installing terraform-ls ${ver} for ${os}"
          curl -sSL -o tfls.zip \
            "https://releases.hashicorp.com/terraform-ls/${ver}/terraform-ls_${ver}_${os}_amd64.zip"
          mkdir -p "$HOME/bin"
          unzip -q tfls.zip -d "$HOME/bin"
          chmod +x "$HOME/bin/terraform-ls"
          echo "$HOME/bin" >> "$GITHUB_PATH"
          echo "terraform-ls installed to $HOME/bin"
      - name: Enhanced Environment Verification (for debugging)
        shell: bash
        run: |
          echo "=== Environment Debugging Information ==="
          echo "Operating System: ${{ runner.os }}"
          echo "Python Version: ${{ matrix.python-version }}"
          echo ""
          echo "=== PATH Environment Variable ==="
          echo "$PATH"
          echo ""
          echo "=== Terraform Executable Location ==="
          if command -v terraform &> /dev/null; then
            echo "terraform found at: $(which terraform)"
            echo "terraform version output:"
            terraform version
          else
            echo "ERROR: terraform not found in PATH"
          fi
          echo ""
          echo "=== terraform-ls Executable Location ==="
          if command -v terraform-ls &> /dev/null; then
            echo "terraform-ls found at: $(which terraform-ls)"
            echo "terraform-ls version output:"
            terraform-ls version
          else
            echo "ERROR: terraform-ls not found in PATH"
          fi
          echo ""
          echo "=== Environment Variables ==="
          echo "TERRAFORM_CLI_PATH: ${TERRAFORM_CLI_PATH:-'not set'}"
          echo "CHECKPOINT_DISABLE: ${CHECKPOINT_DISABLE:-'not set'}"
      - name: Install uv
        shell: bash
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Cache uv virtualenv
        id: cache-uv
        uses: actions/cache@v3
        with:
          path: .venv
          key: uv-venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('uv.lock') }}
      - name: Create virtual environment
        shell: bash
        run: |
          if [ ! -d ".venv" ]; then
            uv venv
          fi
      - name: Install dependencies
        shell: bash
        run: uv pip install -e ".[dev]"
      - name: Test with pytest
        shell: bash
        env:
          CHECKPOINT_DISABLE: 1  # Disable Terraform network calls to prevent hangs
        run: uv run poe test
